version: '3.8'

services:
  eureka-server:
    build:
      context: ./EurekaServer
    ports:
      - "8761:8761"
    networks:
      - microservice-net

  user-service:
    build:
      context: ./UserService
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://EurekaServer:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - microservice-net

  products-service:
    build:
      context: ./ProductsService
    ports:
      - "8081:8081"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://EurekaServer:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - microservice-net

networks:
  microservice-net:
